OrdererOrgs:
  - Name: Orderer
    Domain: network.c1
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        SANS:
          - localhost
          - 127.0.0.1
          - ::1
          - orderer0-network-c1
          - orderer0-network-c1.network-c1.svc.cluster.local
          - orderer0.network.c1
PeerOrgs:
  - Name: Org1
    Domain: org1.network.c1
    EnableNodeOUs: true
    Template:
      Count: 3
      SANS:
        - localhost
        - 127.0.0.1
        - ::1
        - "{{.Hostname}}-org1-network-c1"
        - "{{.Hostname}}-org1-network-c1.network-c1.svc.cluster.local"
        - "{{.Hostname}}.org1.network.c1"
        - "peers-org1-network-c1"
    Users:
      Count: 1
