
apiVersion: v1
kind: Service
metadata:
  name: orderer0-network-c1
  namespace: network-c1
spec:
  type: ClusterIP
  selector:
    component: "orderer0.network.c1"
  ports:
  - name: "listen"
    port: 7050
    protocol: TCP
    targetPort: 7050
  - name: "operations"
    port: 8443
    protocol: TCP
    targetPort: 8443

---

apiVersion: v1
kind: Service
metadata:
  name: ordering-service-network-c1
  namespace: network-c1
spec:
  type: ClusterIP
  selector:
    type: orderer
  ports:
  - name: "listen"
    port: 7050
    protocol: TCP
    targetPort: 7050
